version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - deploy
#      - build
#      - deploy:
#          requires:
#            - build

jobs:
  build:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run:
          name: install
          command: yarn
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
  deploy:
    docker:
      - image: circleci/python:3.8.5
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - add_ssh_keys:
          fingerprints:
            - "95:d9:3b:5e:3e:94:9c:07:0d:f5:93:b2:82:65:21:25"
       - run:
           name: connect-ssh
           command: |
             ssh -o 'IdentitiesOnly yes' $SSH_USER@$SSH_SERVER "pwd"
#      - run:
#          name: deploy
#          command: chmod +x ./deploy.sh && ./deploy.sh

