version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

jobs:
  build:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run:
          name: install
          command: yarn
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
  deploy:
    docker:
      - image: circleci/python:3.8.5
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: deploy
          command: chmod +x ./deploy.sh && ./deploy.sh

