version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - deploy
#      - build
#      - deploy:
#          requires:
#            - build

jobs:
  build:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run:
          name: install
          command: yarn
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
  deploy:
    docker:
      - image: circleci/python:3.8.5
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - add_ssh_keys:
          fingerprints:
            - "5a:c0:e8:26:a8:ca:e7:64:ce:5d:ff:15:80:30:89:4d"
      - run:
          name: connect-ssh
          command: |
            cat ~/.ssh/config
            cat ~/.ssh/id_rsa_5ac0e826a8cae764ce5dff158030894d
            ssh -vvv ubuntu@54.242.60.92 "pwd"
#      - run:
#          name: deploy
#          command: chmod +x ./deploy.sh && ./deploy.sh

