orbs:
  aws-ecr: circleci/aws-ecr@6.15.0
  aws-ecs: circleci/aws-ecs@1.4.0

version: 2.1

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image
          repo: ${MY_APP_PREFIX}
          dockerhub-username: $DOCKERHUB_USER
          dockerhub-password: $DOCKERHUB_PASSWORD
          docker-login: true
      - aws-ecs/deploy-service-update:
        requires:
          - aws-ecr/build-and-push-image
        family: '${MY_APP_PREFIX}-service'
        cluster-name: '${MY_APP_PREFIX}-cluster'
        container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'

jobs:
  build:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run:
          name: install
          command: yarn
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
  deploy:
    docker:
      - image: $DOCKERHUB_IMAGE
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

