orbs:
  aws-ecr: circleci/aws-ecr@6.15.0
  aws-ecs: circleci/aws-ecs@1.4.0

version: 2.1

workflows:
  build:
    jobs:
      - build
    deploy:
      requires:
        - build

jobs:
  build:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run:
          name: install
          command: yarn
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
  deploy:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run:
          name: deploy
          command: chmod +x ./deploy.sh && ./deploy.sh

